# Input match : unit match
convertableUnits = {
    # Temperature
    "c":            "celcius",
    "celcius":      "celcius",
    "f":            "fahrenheit",
    "fahrenheit":   "fahrenheit",
    "k":            "kelvin",
    "kelvin":       "kelvin",

    # Volume 
    "tsp":          "teaspoon-metric",
    "teaspoon":     "teaspoon-metric",
    "teaspoons":    "teaspoon-metric",
    "tbsp":         "tablespoon-metric",
    "tablespoon":   "tablespoon-metric",
    "tablespoons":  "tablespoon-metric",
    "fl oz":        "floz-us",
    "fl oz us":     "floz-us",
    "fluid ounce":  "floz-us",
    "fluid ounce us":"floz-us",
    "fl oz imp":     "floz-imp",
    "fluid ounce imp":"floz-imp",
    "cup":          "cups-us",
    "cups":         "cups-us",
    "cup us":       "cups-us",
    "cups us":      "cups-us",
    "cup imp":      "cups-imp",
    "cups imp":     "cups-imp",
    "ml":           "milliliter",
    "milliliter":   "milliliter",
    "cm3":          "cm3",
    "ltr":          "liter",
    "liter":        "liter",
    "m3":           "m3",
    "meter cube":   "m3",
    "in3":          "in3",
    "inch cube":    "in3",
    "ft3":          "ft3",
    "pt":           "pint-us",
    "pint":         "pint-us",
    "pints":        "pint-us",
    "pint us":      "pint-us",
    "pt imp":       "pint-imp",
    "pint imp":     "pint-imp",
    "pints imp":    "pint-imp",
    "qt":           "quart-us",
    "quart":        "quart-us",
    "quart us":     "quart-us",
    "qt imp":       "quart-imp",
    "quart imp":    "quart-imp",
    "gal US":       "gallon-us",
    "gallon":       "gallon-us",
    "gallons US":   "gallon-us",
    "gal imp":      "gallon-imp",
    "gallons imp":  "gallon-imp",
    
    # Weight
    "lb":           "pounds",
    "pound":        "pounds",
    "pounds":       "pounds",
    "oz":           "ounces",
    "ounce":        "ounces",
    "shton":        "short-ton",
    "short ton":    "short-ton", 
    "lton":         "long-ton",
    "long ton":     "long-ton", 
    "g":            "grams",
    "gram":         "grams", 
    "grams":        "grams", 
    "kg":           "kilos",
    "kilo":         "kilos", 
    "kilos":        "kilos",  
    "kilogram":     "kilos",
    "tonne":        "metric-tonnes", 
    "tonnes":       "metric-tonnes",  
    "metric tonnes":"metric-tonnes",
 
    # Length
    "in":           "inches",
    "inch":         "inches",
    "inches":       "inches",
    "ft":           "feet",
    "foot":         "feet",
    "feet":         "feet",
    "yd":           "yards",
    "yard":         "yards",
    "yards":        "yards",
    "mi":           "miles",
    "mile":         "miles",
    "miles":        "miles",
    "mm":           "millimeters",
    "millimeter":   "millimeters",
    "millimeters":  "millimeters",
    "cm":           "centimeters",
    "centimeter":   "centimeters",
    "centimeters":  "centimeters",
    "m":            "meters",
    "meter":        "meters",
    "meters":       "meters",
    "km":           "kilometers",
    "kilometer":    "kilometers",
    "kilometers":   "kilometers",
}

def parse_units(input_unit):
    if input_unit in convertableUnits:
        return convertableUnits.get(input_unit)
    else:
        return False

unitsTheWorldShouldJustGetRidOf = {
    "tbsp us":      "tablespoon-us",
    "tablespoon us":"tablespoon-us",
    "tsp imp":       "teaspoon-imp",
    "teaspoon imp":  "teaspoon-imp",
    "tbsp imp":      "tablespoon-imp",
    "tablespoon imp":"tablespoon-imp",
    "tsp us":       "teaspoon-us",  
    "teaspoon us":  "teaspoon-us",
    "cup":          "cups-metric",
    "cups":         "cups-metric",
}